#!/bin/bash

function check_update() {
	cd $(dirname "$0")
	local path=""$(pwd)"/package_list"

	checkupdates > "$path" 2> /dev/null
	pac=$(cat "$path" | wc -l)

	pacaur -k | sed 's/:: aur  //' >> "$path" 2> /dev/null
	aur=$(( $(cat "$path" | wc -l) - $pac ))

	# Align column and add column names
	format_table="$(cat "$path" | column --table --table-columns 'Package','Prev Version','-','New Version')"
	echo "$format_table" > "$path"

	# Add newline to seperate between official repo and aur
	newline=$(cat "$path" | sed "$(($pac + 2))i\ ")
	echo "$newline" > "$path"

	local check=$((pac + aur))
	if [[ "$check" != "0" ]]; then
		echo ""$pac" %{F$THEME_MAIN}%{F-} "$aur""
	else
		echo "0 %{F$THEME_MAIN}%{F-} 0"
	fi
}

case ${1:-checkupdate} in
	'checkupdate')
		check_update
		;;
	'update_pac')
		# set title to Floating for i3 to regconize and make it a float window
		$TERMINAL --title="Floating" -e 'sudo pacman -Syu'
		;;
	'update_aur')
		$TERMINAL --title="Floating" -e 'pacaur -Syua'
		;;
	'list_packages')
		cd $(dirname "$0")
		cmd="cat "$(pwd)"/package_list"
		$TERMINAL --title="Floating" -e "$cmd" --hold
		;;
	*)
		;;
esac
