#!/bin/bash

function check_update() {
	cd "$(dirname "$0")" || exit 1
	local path
	
	path="$(pwd)/package_list"

	checkupdates > "$path" 2> /dev/null
	pac=$(wc -l < "$path")

	pacaur -k | sed 's/:: aur  //' >> "$path" 2> /dev/null
	aur=$(( $(wc -l < "$path") - pac ))

	# Align column and add column names
	format_table="$(column --table --table-columns 'Package','Prev Version','-','New Version' < "$path")"
	echo "$format_table" > "$path"

	# Add newline to seperate between official repo and aur
	newline=$(sed "$((pac + 2))i"'\ ' < "$path")
	echo "$newline" > "$path"

	local check=$((pac + aur))
	if [[ "$check" != "0" ]]; then
		echo "$pac %{F$THEME_MAIN}%{F-} $aur"
	else
		echo "0 %{F$THEME_MAIN}%{F-} 0"
	fi
}

action=${1:-checkupdate}

case "$action" in
	'checkupdate')
		check_update
		;;
	'update_pac')
		# set title to Floating for i3 to regconize and make it a float window
		$TERMINAL --title="Floating" -e 'sudo pacman -Syu'
		;;
	'update_aur')
		$TERMINAL --title="Floating" -e 'pacaur -Syua'
		;;
	'list_packages')
		cd "$(dirname "$0")" || exit 1
		cmd="cat $(pwd)/package_list"
		$TERMINAL --title="Floating" -e "$cmd" --hold
		;;
	*)
		;;
esac
