#!/bin/env bash

# Usage:
# source this file in ~/.bashrc
# $ sd    # [s]earch [d]irectory

# Dependencies:
# fzf
# fd

function sd() {
	local USAGE='Usage: sd [help|<directory pattern>]'
	local HELP=''
	local EXCLUDE_PATTERN

	HELP=('sd <command>'
	'Change directory by using fzf to filter path'
	'Commands:'
	'   h, help                print this help message'
	'   <directory pattern>    search pattern for dirname, a regular expression')

	EXCLUDE_PATTERN+=\{
	EXCLUDE_PATTERN+=node_modules,.cache,.cargo,.dropbox,.git,.local,site-packages,
	EXCLUDE_PATTERN+=.config/google-chrome
	EXCLUDE_PATTERN+=\}

	function usage() { # {{{
		echo "$USAGE"
	}
	# }}}
	function help() { # {{{
		printf '%s\n' "${HELP[@]}"
	}
	# }}}
	function find_dirs() { # {{{
		local dir_pattern="${1:-}"
		if [[ "$#" == 2 ]]; then
			local path="$2"
		fi
		fd --type directory --no-ignore --hidden --exclude="$EXCLUDE_PATTERN" "$dir_pattern" "$path"
	}
	# }}}
	function cd_fzf() { # {{{
		local dir_pattern="${1:-}"
		local root
		local directory

		root=$(git rev-parse --show-toplevel 2> /dev/null)
		directory=$(find_dirs "$dir_pattern" "${root:-$HOME}" |
			fzf -1 --height=15 --prompt=cd:\ )
		if [[ "$directory" != '' ]]; then
			echo cd "$(pwd)"/"$directory"
			# shellcheck disable=SC2164
			cd "$directory"
		fi
	}
	# }}}
	function cd_fzf_with_ranger() { # {{{
		find_dirs | fzf --prompt='cd: '
	}
	# }}}
	function main() { # {{{
		local cmd="${1:-}"

		case "$#" in
			0)
				cd_fzf ;;
			1)
				case "$cmd" in
					-h|--help)
						help ;;
					-r|--ranger)
						cd_fzf_with_ranger ;;
					*)
						cd_fzf "$cmd" ;;
				esac ;;
			*)
			usage ;;
		esac
	}
	# }}}

	main "$@"
	unset -f usage
	unset -f help
	unset -f find_dirs
	unset -f cd_fzf
	unset -f cd_fzf_with_ranger
	unset -f main
}
