#!/bin/env bash

# Notify to take a break, sleep for 5 minutes then notify to get back to work

# Dependencies:
# dunstify

: "${REST_INTERVAL:=$((60 * 5))}"
: "${WORK_ICON:="$HOME/.icons/dunst/rest-back-to-work.png"}"
: "${REST_ICON:="$HOME/.icons/dunst/rest-take-a-break.png"}"
WORK_IDIOMS=(
'Rest time is over. Get back to work you lazy ass'
'Get the fuck back to work'
'If you could get back to work, that would be great'
'Back to work bitch'
)
REST_IDIOMS=(
'Take a break!'
"Let's go smoke a Pepsi"
"It's okay to take a break now"
'Get some air'
)
: "${REST_IDIOMS_LINES:=${#REST_IDIOMS[@]}}"
: "${WORK_IDIOMS_LINES:=${#WORK_IDIOMS[@]}}"

function notify() { # {{{
	local title="$1" message="$2" icon="$3"
	if [[ -x /usr/share/dunstify ]]; then
		dunstify --replace=101 --urgency=low --icon="$icon" "$message"
	else
		notify-send --urgency=low --icon="$icon" "$title" "$message"
	fi
}
# }}}
function take_a_break() { # {{{
	local rest_idiom=${REST_IDIOMS[$((RANDOM % REST_IDIOMS_LINES))]}
	notify 'take_a_break' "$rest_idiom" "$REST_ICON"
	sleep "$REST_INTERVAL"
	back_to_work
}
# }}}
function back_to_work() { # {{{
	local work_idiom=${WORK_IDIOMS[$((RANDOM % WORK_IDIOMS_LINES))]}
	notify 'take_a_break' "$work_idiom" "$WORK_ICON"
}
# }}}

take_a_break
